### ISSUE TITLE
[BUG] Two-tower model.evaluate() gives error after model is trained and compiled twice

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/models#520]
### Bug description

I get the following error from `model.evaluate()` step, when I train TT model second time.

```
WARNING:absl:Found untraced functions such as model_context_1_layer_call_fn, model_context_1_layer_call_and_return_conditional_losses, parallel_block_2_layer_call_fn, parallel_block_2_layer_call_and_return_conditional_losses, sequential_block_20_layer_call_fn while saving (showing 5 of 18). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: /tmp/tmp0z92l8wq/assets
INFO:tensorflow:Assets written to: /tmp/tmp0z92l8wq/assets
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:merlin_models:The sampler InBatchSampler returned no samples for this batch.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File <timed exec>:1, in <module>

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py:775, in RetrievalModel.evaluate(self, x, y, item_corpus, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, return_dict, **kwargs)
    772     if isinstance(self.prediction_tasks[0], ItemRetrievalTask):
    773         self.prediction_tasks[0].set_retrieval_cache_query(True)  # type: ignore
--> 775 return super().evaluate(
    776     x,
    777     y,
    778     batch_size,
    779     verbose,
    780     sample_weight,
    781     steps,
    782     callbacks,
    783     max_queue_size,
    784     workers,
    785     use_multiprocessing,
    786     return_dict,
    787     **kwargs,
    788 )

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py:626, in Model.evaluate(self, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, return_dict, **kwargs)
    609 def evaluate(
    610     self,
    611     x=None,
   (...)
    622     **kwargs,
    623 ):
    624     x = _maybe_convert_merlin_dataset(x, batch_size, shuffle=False, **kwargs)
--> 626     return super().evaluate(
    627         x,
    628         y,
    629         batch_size,
    630         verbose,
    631         sample_weight,
    632         steps,
    633         callbacks,
    634         max_queue_size,
    635         workers,
    636         use_multiprocessing,
    637         return_dict,
    638         **kwargs,
    639     )

File /usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File /tmp/__autograph_generated_file9ydpjn5c.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__test_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py:485, in Model.test_step(self, data)
    480 outputs = self.prediction_output(x, y, testing=True)
    482 if getattr(self, "pre_eval_topk", None) is not None:
    483     # During eval, the retrieval-task only returns positive scores
    484     # so we need to retrieve top-k negative scores to compute the loss
--> 485     outputs = self.pre_eval_topk.call_outputs(outputs)
    487 self.compute_loss(x, outputs.targets, outputs.predictions, sample_weight)
    488 metrics = self.compute_metrics(
    489     x, outputs.targets, outputs.predictions, sample_weight, training=False
    490 )

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/blocks/core/index.py:252, in TopKIndexBlock.call_outputs(self, outputs, training, **kwargs)
    233 def call_outputs(
    234     self, outputs: PredictionOutput, training=False, **kwargs
    235 ) -> "PredictionOutput":
    236     """
    237     Retrieve top-k negative scores for evaluation.
    238 
   (...)
    250         the scores for the top-k implicit negatives.
    251     """
--> 252     queries = self.context["query"]
    253     pred_top_scores, top_ids = self(queries, k=self._k)
    255     targets_sorted = tf.cast(
    256         tf.expand_dims(outputs.positive_item_ids, -1) == top_ids, tf.float32
    257     )

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/blocks/core/base.py:120, in ModelContext.__getitem__(self, item)
    118 else:
    119     item = str(item)
--> 120 return self.named_variables[item]

KeyError: in user code:

    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1557, in test_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1546, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1535, in run_step  **
        outputs = model.test_step(data)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 485, in test_step
        outputs = self.pre_eval_topk.call_outputs(outputs)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/blocks/core/index.py", line 252, in call_outputs
        queries = self.context["query"]
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/blocks/core/base.py", line 120, in __getitem__
        return self.named_variables[item]

    KeyError: 'query'
```
### Expected behavior
we should be able to train  and perform evaluation step TT model as many times as we want without getting error.

YOU CAN USE THIS CODE TO REPRODUCE THE ERROR:

STEP 1:

```
from merlin.schema.tags import Tags

import merlin.models.tf as mm
from merlin.io.dataset import Dataset

import tensorflow as tf
from merlin.datasets.synthetic import generate_data

DATA_FOLDER = os.environ.get("DATA_FOLDER", "/workspace/data/")
NUM_ROWS = os.environ.get("NUM_ROWS", 1000000)
train, valid = generate_data("aliccp-raw", int(NUM_ROWS), set_sizes=(0.7, 0.3))
# define output path for the processed parquet files
output_path = os.path.join(DATA_FOLDER, "processed")

user_id = ["user_id"] >> Categorify() >> TagAsUserID()
item_id = ["item_id"] >> Categorify() >> TagAsItemID()

item_features = ["item_category", "item_shop", "item_brand"] >> Categorify() >> TagAsItemFeatures()

user_features = (
    [
        "user_shops",
        "user_profile",
        "user_group",
    ]
    >> Categorify()
    >> TagAsUserFeatures()
)

inputs = user_id + item_id + item_features + user_features + ["click"]
outputs = inputs >> Filter(f=lambda df: df["click"] == 1)
from merlin.datasets.ecommerce import transform_aliccp
transform_aliccp((train, valid), output_path, nvt_workflow=outputs)

train = Dataset(os.path.join(output_path, "train", "*.parquet"))
valid = Dataset(os.path.join(output_path, "valid", "*.parquet"))

schema = train.schema
schema = schema.select_by_tag([Tags.ITEM_ID, Tags.USER_ID, Tags.ITEM, Tags.USER])
retrieval_task = mm.ItemRetrievalTask(
    samplers=[mm.InBatchSampler()],
    schema=schema,
    logits_temperature=1.3,
    store_negative_ids=True,
)
```
STEP 2 (RUN THIS PART TWICE TO REPRO THE ERROR).
```
model = mm.TwoTowerModel(
    schema,
    query_tower=mm.MLPBlock(
        [128], 
        activation='selu',
    ),
    item_tower=mm.MLPBlock(
        [128],
        activation='selu',
    ), 
    embedding_options=mm.EmbeddingOptions(
        infer_embedding_sizes=True,  
        embeddings_l2_reg=2.03e-05
    ),
    prediction_tasks=retrieval_task,
    l2_normalization=False,
)
model.compile(optimizer="adam", run_eagerly=False, metrics=[mm.RecallAt(20), mm.NDCGAt(20)])
model.fit(train, batch_size=8192, epochs=1)

eval_metrics = model.evaluate(
    valid,
    batch_size=4096,
    return_dict=True,
    item_corpus=train                                                          
)
```

### Environment details
- Merlin version: 
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

`merlin-tensorflow-training:22.05` container with the latest main branches pulled.

**Comment by viswa-nvidia** [comment]
@rnyak ,  please triage your bug with severity and priority

**Comment by oliverholworthy** [comment]
the ItemRetrievalTask is the part that sets up the query context.

https://github.com/NVIDIA-Merlin/models/blob/c22333f15e45babfe9093282270af21ef6c4ad25/merlin/models/tf/blocks/retrieval/base.py#L207-L216

However this ModelContext is reset when the model is re-initialized. 

https://github.com/NVIDIA-Merlin/models/blob/c22333f15e45babfe9093282270af21ef6c4ad25/merlin/models/tf/models/base.py#L175

Which is why I think when the model is re-evaluated without the item retrieval task, we get the KeyError. 

One option would be to re-evaluate the retrieval task along with the model so that it get's rebuild and sets the query context correctly again

```
retrieval_task = mm.ItemRetrievalTask(
    samplers=[mm.InBatchSampler()],
    schema=schema,
    logits_temperature=1.3,
    store_negative_ids=True,
)
```

**Comment by rnyak** [comment]
@oliverholworthy thanks. re-running `retrieval_task` block before retraining and evaluating helped. closing this issue for now.
