### ISSUE TITLE
[BUG] Two-tower model model.evaluate() step gives error

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/models#569]
### Bug description
After I pulled the latest branch, I am getting the error from `model.evaluate()` step, after training a Two-Tower model.

```
eval_metrics = model.evaluate(
    valid,
    batch_size=512,
    return_dict=True,
    item_corpus=train                                                          
)

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [15], in <cell line: 1>()
----> 1 eval_metrics = model.evaluate(
      2     valid,
      3     batch_size=512,
      4     return_dict=True,
      5     item_corpus=train                                                          
      6 )

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py:876, in RetrievalModel.evaluate(self, x, y, item_corpus, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, return_dict, **kwargs)
    869     if len(topk_metrics) == 0:
    870         # TODO: Decouple the evaluation of RetrievalModel from the need of using
    871         # at least one TopkMetric (how to infer the k for TopKIndexBlock?)
    872         raise ValueError(
    873             "RetrievalModel evaluation requires at least "
    874             "one TopkMetric (e.g., RecallAt(5), NDCGAt(10))."
    875         )
--> 876     self.pre_eval_topk = TopKIndexBlock.from_block(
    877         item_block,
    878         data=item_corpus,
    879         k=tf.reduce_max([metric.k for metric in topk_metrics]),
    880         context=self.context,
    881         **kwargs,
    882     )
    883 else:
    884     self.pre_eval_topk.update_from_block(item_block, item_corpus)

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/index.py:208, in TopKIndexBlock.from_block(cls, block, data, k, id_column, **kwargs)
    179 @classmethod
    180 def from_block(  # type: ignore
    181     cls,
   (...)
    186     **kwargs,
    187 ) -> "TopKIndexBlock":
    188     """
    189     class method to build candidates embeddings from
    190     applying `block` to a dataset of features `data`
   (...)
    206         a schema with an item-id Tag.
    207     """
--> 208     return super().from_block(block=block, data=data, id_column=id_column, k=k, **kwargs)

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/index.py:81, in IndexBlock.from_block(cls, block, data, id_column, **kwargs)
     64 @classmethod
     65 def from_block(
     66     cls, block: Block, data: merlin.io.Dataset, id_column: Optional[str] = None, **kwargs
     67 ) -> "IndexBlock":
     68     """Build candidates embeddings from applying `block` to a dataset of features `data`.
     69 
     70     Parameters:
   (...)
     79         a schema with an item-id Tag.
     80     """
---> 81     embedding_df = cls.get_candidates_dataset(block, data, id_column)
     82     return cls.from_dataset(embedding_df, **kwargs)

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/index.py:112, in IndexBlock.get_candidates_dataset(cls, block, data, id_column)
    109     if tagged.column_schemas:
    110         id_column = tagged.first.name
--> 112 model_encode = TFModelEncode(model=block, output_concat_func=np.concatenate)
    114 data = data.to_ddf()
    115 embedding_ddf = data.map_partitions(model_encode, filter_input_columns=[id_column])

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/utils/batch_utils.py:80, in TFModelEncode.__init__(self, model, output_names, batch_size, save_path, block_load_func, schema, output_concat_func)
     69 def __init__(
     70     self,
     71     model: tp.Union[Model, tf.keras.Model],
   (...)
     77     output_concat_func=None,
     78 ):
     79     save_path = save_path or tempfile.mkdtemp()
---> 80     model.save(save_path)
     82     model_load_func = block_load_func if block_load_func else tf.keras.models.load_model
     83     if not output_names:

File /usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py:1147, in func_graph_from_py_func.<locals>.autograph_handler(*args, **kwargs)
   1145 except Exception as e:  # pylint:disable=broad-except
   1146   if hasattr(e, "ag_error_metadata"):
-> 1147     raise e.ag_error_metadata.to_exception(e)
   1148   else:
   1149     raise

TypeError: in user code:

    File "/usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py", line 138, in _wrapped_model  *
        outputs = model(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/config/schema.py", line 58, in __call__  *
        return super().__call__(*args, **kwargs)

    TypeError: tf__call() takes 2 positional arguments but 3 were given

```

### Steps/Code to reproduce bug

You can use [05-Retrieval-Model.ipynb](https://github.com/NVIDIA-Merlin/models/blob/main/examples/05-Retrieval-Model.ipynb) notebook to repro the error. After `model.fit()` step run the following:

```
eval_metrics = model.evaluate(
    valid,
    batch_size=512,
    return_dict=True,
    item_corpus=train                                                          
)
```

### Environment details
- Merlin version: 
- Platform: Docker container on NGC
- Python version: 3.8.10
- PyTorch version (GPU?):
- Tensorflow version (GPU?): '2.8.0'

Using 22.05 merlin-tensorflow-training container with the latest branches pulled.

**Comment by viswa-nvidia** [comment]
@rnyak , please triage this bug

**Comment by rnyak** [comment]
I get this error with TF version == 2.8 but could make it work if I upgrade the TF version to 2.9.
