### ISSUE TITLE
[BUG]  one_hot arg is not working in  ToTarget(Block) class

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/models#844]
### Steps/Code to reproduce bug

I am getting the following error when I set `one_hot=True` in the ToTarget as `mm.Loader(train, batch_size=128, transform=mm.ToTarget(schema, "user_country", one_hot=True))`

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Cell In [11], line 2
      1 model.compile(run_eagerly=False, optimizer='adam')
----> 2 model.fit(loader, epochs=1)

File /usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py:856, in BaseModel.fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing, train_metrics_steps, pre, **kwargs)
    853     self._reset_compile_cache()
    854     self.train_pre = pre
--> 856 out = super().fit(**fit_kwargs)
    858 if pre:
    859     del self.train_pre

File /usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py:54, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52 try:
     53   ctx.ensure_initialized()
---> 54   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                       inputs, attrs, num_outputs)
     56 except core._NotOkStatusException as e:
     57   if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'Reshape' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 982, in launch_instance
      app.start()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py", line 712, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
      await result
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
      res = shell.run_cell(
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2885, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2940, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3139, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3318, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3378, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_234/224013731.py", line 2, in <module>
      model.fit(loader, epochs=1)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 856, in fit
      out = super().fit(**fit_kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 677, in train_step
      outputs = self.call_train_test(x, y, sample_weight=sample_weight, training=True)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 605, in call_train_test
      self.adjust_predictions_and_targets(predictions, targets)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 662, in adjust_predictions_and_targets
      targets[k] = tf.reshape(targets[k], tf.shape(predictions[k]))
Node: 'Reshape'
Detected at node 'Reshape' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 982, in launch_instance
      app.start()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py", line 712, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
      await result
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
      res = shell.run_cell(
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2885, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2940, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3139, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3318, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3378, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_234/224013731.py", line 2, in <module>
      model.fit(loader, epochs=1)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 856, in fit
      out = super().fit(**fit_kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 677, in train_step
      outputs = self.call_train_test(x, y, sample_weight=sample_weight, training=True)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 605, in call_train_test
      self.adjust_predictions_and_targets(predictions, targets)
    File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 662, in adjust_predictions_and_targets
      targets[k] = tf.reshape(targets[k], tf.shape(predictions[k]))
Node: 'Reshape'
2 root error(s) found.
  (0) INVALID_ARGUMENT:  Input to reshape is a tensor with 128 values, but the requested shape has 8064
	 [[{{node Reshape}}]]
	 [[gradient_tape/model_3/xl_net_block_3/prepare_transformer_inputs_4/RaggedToTensor/strided_slice/_250]]
  (1) INVALID_ARGUMENT:  Input to reshape is a tensor with 128 values, but the requested shape has 8064
	 [[{{node Reshape}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_18262]
```

Please run the code below to repro the issue. you can see that when generate a batch from the Loader, the target is not one-hot encoded. 

```
from merlin.datasets.synthetic import generate_data
train = generate_data("sequence-testing", num_rows=1000)
schema = train.schema.select_by_name(
    ["item_id_seq", "categories", "user_country"]
)
schema["user_country"] = schema["user_country"].with_tags(
    schema["user_country"].tags + "target"
)
train.schema = schema

model = mm.Model(
    mm.InputBlockV2(
        schema,
        embeddings=mm.Embeddings(schema, sequence_combiner=None),
    ),
    mm.XLNetBlock(
        d_model=48,
        n_head=8,
        n_layer=2,
        post='sequence_mean',
    ),
    mm.CategoricalOutput(
        to_call=schema["user_country"],
    ),
)

loader = mm.Loader(train, batch_size=128, transform=mm.ToTarget(schema, "user_country", one_hot=True))

# print the label from the batch you can see that it is not one-hot encoded
batch = next(iter(loader))
batch[1]

model.compile(run_eagerly=False, optimizer='adam')
model.fit(loader, epochs=1)
```

**Comment by viswa-nvidia** [comment]
@rnyak , please triage this bug
